server:
  servlet:
    context-path: 
  port: ${PORT:9444}

spring:
  datasource:
    url: jdbc:postgresql://ec2-18-214-119-135.compute-1.amazonaws.com:5432/d3sq26q4ekv73e
    username: tjamaghsnopkzw
    password: 001ed5edb0c8cdb660cfde56c6c0f70463921834083dc3b85a1d2346320b83e2
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: ${HIBERNATE_SHOW_SQL:false}
    properties:
      hibernate:
        generate_statistics: ${HIBERNATE_STATISTICS:false}
        temp:
          use_jdbc_metadata_defaults: false

oauth2-config:
  client-id: ${OAUTH2_CLIENT_ID:bussola-contabil-client}
  client-secret: ${OAUTH2_CLIENT_SECRET:bussola-contabil-secret}
  server-url: ${OAUTH2_SERVER_URL:https://development-oauth-server.herokuapp.com}

oauth:
  service:
    name: oauth-service
    url: ${OAUTH2_SERVER_URL:https://development-oauth-server.herokuapp.com}
    
security:
  oauth2:
    client:
      clientId: ${oauth2-config.client-id}
      clientSecret: ${oauth2-config.client-secret}
      accessTokenUri: ${oauth2-config.server-url}/oauth/token
      userAuthorizationUri: ${oauth2-config.server-url}/oauth/authorize

    resource:
      userInfoUri: ${oauth2-config.server-url}/user/info
      tokenInfoUri: ${oauth2-config.server-url}/oauth/check_token